# Generated by Django 5.1.1 on 2026-04-15 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_owner_cat_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achiev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AchievCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achiev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.achiev')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='achiev',
            field=models.ManyToManyField(through='cats.AchievCat', to='cats.achiev'),
        ),
    ]
