# Generated by Django 5.1.1 on 2026-04-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_achiev_achievcat_cat_achiev'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achiev',
            new_name='Achievement',
        ),
        migrations.RenameModel(
            old_name='AchievCat',
            new_name='AchievementCat',
        ),
        migrations.RenameField(
            model_name='achievementcat',
            old_name='achiev',
            new_name='achievement',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='achiev',
        ),
        migrations.AddField(
            model_name='cat',
            name='achievements',
            field=models.ManyToManyField(through='cats.AchievementCat', to='cats.achievement'),
        ),
    ]
